apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

images:
- name: ghcr.io/plus-jia/gitops-blog
  newName: ghcr.io/plus-jia/gitops-blog
  newTag: d8b7e258a07474bc51d0059ffad0c0aa50bb4a71
