apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

images:
- name: ghcr.io/plus-jia/gitops-blog
  newName: ghcr.io/plus-jia/gitops-blog
  newTag: 932453bd321cd4f72adcadf0132b4afb94ae4c15
