apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

images:
- name: ghcr.io/plus-jia/gitops-blog
  newName: ghcr.io/plus-jia/gitops-blog
  newTag: 0756a410b28cbb9d65aa762e635d24098fa7093a
