apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog-dev
resources:
  - ../../base
images:
  - name: ghcr.io/example/gitops-blog-frontend
    newTag: 0cbc86d6ac6c835ec7ca9a95bef47b3ca85a47ba
